---
- name: APT upgrade k3s_cluster
  hosts: k3s_cluster
  gather_facts: true
  become: true
  tasks:
    - name: APT upgrade full
      apt:
        upgrade: full
        update_cache: true
        autoremove: true
        autoclean: true
